export const myData = {
  profile: { id: "me", name: "나" },
  schedules: [
    {
      id: "my_1",
      title: "시데레우스 자첫 아주 기나긴 제목 테스트",
      date: "2026-06-16",
      time: "20:00",
      genre: "뮤지컬",
      isPending: false,
      actors: "강찬, 정민, 안재영",
      place: "플러스씨어터",
      seat: "OP석 3열",
      price: "66,000원",
      shop: "인터파크",
      memo: "드디어 자첫!",
    },
    {
      id: "my_2",
      title: "브카라 종공 회차 가고 싶다",
      date: "2026-06-21",
      time: "18:00",
      genre: "뮤지컬",
      isPending: true,
      actors: "미정",
      place: "링크아트센터 드림1관",
      seat: "",
      price: "",
      shop: "",
      memo: "",
    },
  ],
};

export const favoriteActors = [
  {
    id: "actor1",
    name: "강찬",
    castings: [
      {
        id: "a1_1",
        showName: "등등곡",
        place: "예스24스테이지 1관",
        date: "2026-06-15",
        time: "20:00",
        event: "커튼콜 데이",
        actors: "김재범, 안지환, 강찬, 박선영, 황두현",
      },
      {
        id: "a1_2",
        showName: "등등곡",
        place: "예스24스테이지 1관",
        date: "2026-06-24",
        time: "20:00",
        event: "",
        actors: "유승현, 김바다, 강찬, 김경록, 이경신",
      },
      {
        id: "a1_3",
        showName: "등등곡",
        place: "예스24스테이지 1관",
        date: "2026-07-02",
        time: "20:00",
        event: "스페셜 웰컴데이",
        actors: "유승현, 김바다, 강찬, 박선영, 임태현",
      },
      {
        id: "a1_4",
        showName: "등등곡",
        place: "예스24스테이지 1관",
        date: "2026-07-08",
        time: "16:00",
        event: "마티네 할인",
        actors: "김재범, 정재환, 강찬, 김경록, 황두현",
      },
      {
        id: "a1_5",
        showName: "오펀스",
        place: "대학로 아트원씨어터",
        date: "2026-07-15",
        time: "20:00",
        event: "오펀스 개막",
        actors: "박지일, 강찬, 최정우",
      },
      {
        id: "a1_6",
        showName: "등등곡",
        place: "예스24스테이지 1관",
        date: "2026-07-22",
        time: "20:00",
        event: "스페셜 포토데이",
        actors: "김지철, 안지환, 강찬, 박선영, 임태현",
      },
      {
        id: "a1_7",
        showName: "오펀스",
        place: "대학로 아트원씨어터",
        date: "2026-07-29",
        time: "20:00",
        event: "",
        actors: "이석준, 강찬, 김시유",
      },
      {
        id: "a1_8",
        showName: "나르치스와 골드문트",
        place: "대학로 드림아트센터 3관",
        date: "2026-08-01",
        time: "18:30",
        event: "골드문트 개막",
        actors: "유승현, 강찬",
      },
      {
        id: "a1_9",
        showName: "등등곡",
        place: "예스24스테이지 1관",
        date: "2026-08-05",
        time: "20:00",
        event: "등등곡 총막공 주간",
        actors: "김재범, 정재환, 강찬, 김경록, 황두현",
      },
      {
        id: "a1_10",
        showName: "오펀스",
        place: "대학로 아트원씨어터",
        date: "2026-08-12",
        time: "20:00",
        event: "커튼콜 위크",
        actors: "정민, 강찬, 최정우",
      },
      {
        id: "a1_11",
        showName: "나르치스와 골드문트",
        place: "대학로 드림아트센터 3관",
        date: "2026-08-20",
        time: "20:00",
        event: "스페셜 포토카드 증정",
        actors: "임별, 강찬",
      },
      {
        id: "a1_12",
        showName: "오펀스",
        place: "대학로 아트원씨어터",
        date: "2026-08-29",
        time: "15:00",
        event: "주말 마티네",
        actors: "정민, 강찬, 최정우",
      },
      {
        id: "a1_13",
        showName: "나르치스와 골드문트",
        place: "대학로 드림아트센터 3관",
        date: "2026-09-05",
        time: "15:00",
        event: "주말 2인극",
        actors: "안재영, 강찬",
      },
      {
        id: "a1_14",
        showName: "히스토리 보이즈",
        place: "두산아트센터 연강홀",
        date: "2026-09-15",
        time: "19:30",
        event: "히보 개막일",
        actors: "이대연, 김찬호, 김지온, 손유동, 강찬, 구준모",
      },
      {
        id: "a1_15",
        showName: "나르치스와 골드문트",
        place: "대학로 드림아트센터 3관",
        date: "2026-09-24",
        time: "20:00",
        event: "추석 특별할인",
        actors: "안재영, 강찬",
      },
      {
        id: "a1_16",
        showName: "히스토리 보이즈",
        place: "두산아트센터 연강홀",
        date: "2026-10-01",
        time: "20:00",
        event: "스토리 미터링",
        actors: "김경수, 박은석, 김현진, 윤승우, 강찬, 심수영",
      },
      {
        id: "a1_17",
        showName: "랭보",
        place: "TOM 1관",
        date: "2026-10-03",
        time: "14:00",
        event: "랭보 개막 마티네",
        actors: "홍승안, 김경수, 강찬",
      },
      {
        id: "a1_18",
        showName: "랭보",
        place: "TOM 1관",
        date: "2026-10-14",
        time: "20:00",
        event: "가을 스페셜 티켓",
        actors: "신주협, 김종구, 강찬",
      },
      {
        id: "a1_19",
        showName: "히스토리 보이즈",
        place: "두산아트센터 연강홀",
        date: "2026-11-05",
        time: "20:00",
        event: "전석 하이파이브회",
        actors: "이대연, 김찬호, 김리현, 최정우, 강찬, 구준모",
      },
      {
        id: "a1_20",
        showName: "랭보",
        place: "TOM 1관",
        date: "2026-11-25",
        time: "20:00",
        event: "릴레이 관객 감사제",
        actors: "김리현, 정민, 강찬",
      },
    ],
  },
  {
    id: "actor2",
    name: "안재영",
    castings: [
      {
        id: "a2_1",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-27",
        time: "15:00",
        event: "포토카드 증정",
        actors: "안재영, 안지환, 이상아",
      },
      {
        id: "a2_2",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-28",
        time: "18:30",
        event: "포토카드 증정",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "a2_3",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-30",
        time: "20:00",
        event: "스페셜 커튼콜",
        actors: "안재영, 강병훈, 유낙원",
      },
      {
        id: "a2_4",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-04",
        time: "15:00",
        event: "스페셜 커튼콜",
        actors: "안재영, 기세중, 유낙원",
      },
      {
        id: "a2_5",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-05",
        time: "18:30",
        event: "스페셜 커튼콜",
        actors: "안재영, 안지환, 이상아",
      },
      {
        id: "a2_6",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-07",
        time: "20:00",
        event: "엽서 증정",
        actors: "안재영, 기세중, 이상아",
      },
      {
        id: "a2_7",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-11",
        time: "15:00",
        event: "엽서 증정",
        actors: "안재영, 강병훈, 이상아",
      },
      {
        id: "a2_8",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-12",
        time: "15:00",
        event: "폴라로이드 증정데이",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "a2_9",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-07-15",
        time: "20:00",
        event: "",
        actors: "김주호, 서승원, 안재영, 김지철, 최석진, 조재철",
      },
      {
        id: "a2_10",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-16",
        time: "20:00",
        event: "",
        actors: "안재영, 기세중, 이상아",
      },
      {
        id: "a2_11",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-18",
        time: "15:00",
        event: "",
        actors: "안재영, 기세중, 이상아",
      },
      {
        id: "a2_12",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-18",
        time: "18:30",
        event: "",
        actors: "안재영, 정휘, 이상아",
      },
      {
        id: "a2_13",
        showName: "브라더스 까라마조프",
        place: "リンク아트센터 드림1관",
        date: "2026-07-19",
        time: "18:00",
        event: "",
        actors: "심재현, 양승리, 안재영, 김지철, 박두호, 조재철",
      },
      {
        id: "a2_14",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-07-21",
        time: "20:00",
        event: "",
        actors: "도창선, 서승원, 안재영, 김대현, 최석진, 조영훈",
      },
      {
        id: "a2_15",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-07-22",
        time: "20:00",
        event: "",
        actors: "김주호, 양승리, 안재영, 황민수, 강하경, 조영훈",
      },
      {
        id: "a2_16",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-23",
        time: "20:00",
        event: "",
        actors: "안재영, 강병훈, 이상아",
      },
      {
        id: "a2_17",
        showName: "등등곡 - 고양",
        place: "고양",
        date: "2026-07-25",
        time: "16:00",
        event: "",
        actors: "안재영, 김바다, 강찬, 정서안, 황두현",
      },
      {
        id: "a2_18",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-26",
        time: "18:30",
        event: "",
        actors: "안재영, 강병훈, 유낙원",
      },
      {
        id: "a2_19",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-07-28",
        time: "20:00",
        event: "",
        actors: "김주호, 서승원, 안재영, 이선우, 이준우, 조재철",
      },
      {
        id: "a2_20",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-29",
        time: "19:30",
        event: "관객과의 대화",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "a2_21",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-07-30",
        time: "20:00",
        event: "",
        actors: "도창선, 서승원, 안재영, 김대현, 강하경, 조영훈",
      },
      {
        id: "a2_22",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-31",
        time: "20:00",
        event: "",
        actors: "안재영, 안지환, 이상아",
      },
      {
        id: "a2_23",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-08-01",
        time: "19:00",
        event: "",
        actors: "김주호, 서승원, 안재영, 김대현, 박두호, 조영훈",
      },
      {
        id: "a2_24",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-02",
        time: "18:30",
        event: "",
        actors: "안재영, 정휘, 이상아",
      },
      {
        id: "a2_25",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-08-04",
        time: "20:00",
        event: "",
        actors: "도창선, 조풍래, 안재영, 김지철, 이준우, 조재철",
      },
      {
        id: "a2_26",
        showName: "브라더스 까라마조프",
        place: "링크아트센터 드림1관",
        date: "2026-08-05",
        time: "20:00",
        event: "",
        actors: "심재현, 양승리, 안재영, 김대현, 박두호, 양찬영",
      },
      {
        id: "a2_27",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-06",
        time: "20:00",
        event: "",
        actors: "안재영, 안지환, 유낙원",
      },
    ],
  },
];

export const favoriteShows = [
  {
    id: "show1",
    name: "시데레우스",
    entireSchedules: [
      {
        id: "s1_1",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-25",
        time: "20:00",
        event: "포토카드 증정",
        actors: "박민성, 강병훈, 유낙원",
      },
      {
        id: "s1_2",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-26",
        time: "20:00",
        event: "포토카드 증정",
        actors: "김지철, 강병훈, 유낙원",
      },
      {
        id: "s1_3",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-27",
        time: "15:00",
        event: "포토카드 증정",
        actors: "안재영, 안지환, 이상아",
      },
      {
        id: "s1_4",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-27",
        time: "18:30",
        event: "포토카드 증정",
        actors: "박민성, 기세중, 이상아",
      },
      {
        id: "s1_5",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-28",
        time: "15:00",
        event: "포토카드 증정",
        actors: "김지철, 강병훈, 유낙원",
      },
      {
        id: "s1_6",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-28",
        time: "18:30",
        event: "포토카드 증정",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "s1_7",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-06-30",
        time: "20:00",
        event: "스페셜 커튼콜",
        actors: "안재영, 강병훈, 유낙원",
      },
      {
        id: "s1_8",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-01",
        time: "20:00",
        event: "스페셜 커튼콜",
        actors: "김지철, 안지환, 이상아",
      },
      {
        id: "s1_9",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-02",
        time: "20:00",
        event: "스페셜 커튼콜",
        actors: "박민성, 기세중, 유낙원",
      },
      {
        id: "s1_10",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-03",
        time: "20:00",
        event: "스페셜 커튼콜",
        actors: "박민성, 안지환, 이상아",
      },
      {
        id: "s1_11",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-04",
        time: "15:00",
        event: "스페셜 커튼콜",
        actors: "안재영, 기세중, 유낙원",
      },
      {
        id: "s1_12",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-04",
        time: "18:30",
        event: "스페셜 커튼콜",
        actors: "김지철, 기세중, 유낙원",
      },
      {
        id: "s1_13",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-05",
        time: "15:00",
        event: "스페셜 커튼콜",
        actors: "박민성, 강병훈, 이상아",
      },
      {
        id: "s1_14",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-05",
        time: "18:30",
        event: "스페셜 커튼콜",
        actors: "안재영, 안지환, 이상아",
      },
      {
        id: "s1_15",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-07",
        time: "20:00",
        event: "엽서 증정",
        actors: "안재영, 기세중, 이상아",
      },
      {
        id: "s1_16",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-08",
        time: "20:00",
        event: "엽서 증정",
        actors: "김지철, 강병훈, 이상아",
      },
      {
        id: "s1_17",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-09",
        time: "20:00",
        event: "엽서 증정",
        actors: "박민성, 기세중, 유낙원",
      },
      {
        id: "s1_18",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-10",
        time: "20:00",
        event: "엽서 증정",
        actors: "김지철, 안지환, 유낙원",
      },
      {
        id: "s1_19",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-11",
        time: "15:00",
        event: "엽서 증정",
        actors: "안재영, 강병훈, 이상아",
      },
      {
        id: "s1_20",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-11",
        time: "18:30",
        event: "폴라로이드 증정데이",
        actors: "김지철, 기세중, 이상아",
      },
      {
        id: "s1_21",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-12",
        time: "15:00",
        event: "폴라로이드 증정데이",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "s1_22",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-12",
        time: "18:30",
        event: "폴라로이드 증정데이",
        actors: "박민성, 강병훈, 유낙원",
      },
      {
        id: "s1_23",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-14",
        time: "20:00",
        event: "",
        actors: "김지철, 정휘, 유낙원",
      },
      {
        id: "s1_24",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-15",
        time: "20:00",
        event: "",
        actors: "박민성, 안지환, 이상아",
      },
      {
        id: "s1_25",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-16",
        time: "20:00",
        event: "",
        actors: "안재영, 기세중, 이상아",
      },
      {
        id: "s1_26",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-17",
        time: "15:00",
        event: "",
        actors: "김지철, 강병훈, 유낙원",
      },
      {
        id: "s1_27",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-17",
        time: "18:30",
        event: "",
        actors: "김지철, 안지환, 유낙원",
      },
      {
        id: "s1_28",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-18",
        time: "15:00",
        event: "",
        actors: "안재영, 기세중, 이상아",
      },
      {
        id: "s1_29",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-18",
        time: "18:30",
        event: "",
        actors: "안재영, 정휘, 이상아",
      },
      {
        id: "s1_30",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-19",
        time: "15:00",
        event: "",
        actors: "박민성, 안지환, 유낙원",
      },
      {
        id: "s1_31",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-19",
        time: "18:30",
        event: "",
        actors: "박민성, 강병훈, 유낙원",
      },
      {
        id: "s1_32",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-21",
        time: "20:00",
        event: "",
        actors: "김지철, 강병훈, 유낙원",
      },
      {
        id: "s1_33",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-22",
        time: "20:00",
        event: "",
        actors: "박민성, 안지환, 이상아",
      },
      {
        id: "s1_34",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-23",
        time: "20:00",
        event: "",
        actors: "안재영, 강병훈, 이상아",
      },
      {
        id: "s1_35",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-24",
        time: "20:00",
        event: "",
        actors: "김지철, 안지환, 유낙원",
      },
      {
        id: "s1_36",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-25",
        time: "15:00",
        event: "",
        actors: "박민성, 정휘, 이상아",
      },
      {
        id: "s1_37",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-25",
        time: "18:30",
        event: "",
        actors: "김지철, 안지환, 이상아",
      },
      {
        id: "s1_38",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-26",
        time: "15:00",
        event: "",
        actors: "박민성, 기세중, 유낙원",
      },
      {
        id: "s1_39",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-26",
        time: "18:30",
        event: "",
        actors: "안재영, 강병훈, 유낙원",
      },
      {
        id: "s1_40",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-28",
        time: "19:30",
        event: "관객과의 대화",
        actors: "김지철, 강병훈, 이상아",
      },
      {
        id: "s1_41",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-29",
        time: "19:30",
        event: "관객과의 대화",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "s1_42",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-30",
        time: "20:00",
        event: "",
        actors: "박민성, 강병훈, 유낙원",
      },
      {
        id: "s1_43",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-07-31",
        time: "20:00",
        event: "",
        actors: "안재영, 안지환, 이상아",
      },
      {
        id: "s1_44",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-01",
        time: "15:00",
        event: "",
        actors: "박민성, 강병훈, 유낙원",
      },
      {
        id: "s1_45",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-01",
        time: "18:30",
        event: "",
        actors: "김지철, 안지환, 유낙원",
      },
      {
        id: "s1_46",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-02",
        time: "15:00",
        event: "",
        actors: "박민성, 정휘, 이상아",
      },
      {
        id: "s1_47",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-02",
        time: "18:30",
        event: "",
        actors: "안재영, 정휘, 이상아",
      },
      {
        id: "s1_48",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-04",
        time: "20:00",
        event: "",
        actors: "박민성, 안지환, 이상아",
      },
      {
        id: "s1_49",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-05",
        time: "20:00",
        event: "",
        actors: "김지철, 강병훈, 이상아",
      },
      {
        id: "s1_50",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-06",
        time: "20:00",
        event: "",
        actors: "안재영, 안지환, 유낙원",
      },
      {
        id: "s1_51",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-07",
        time: "20:00",
        event: "",
        actors: "박민성, 정휘, 유낙원",
      },
      {
        id: "s1_52",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-08",
        time: "15:00",
        event: "",
        actors: "안재영, 강병훈, 이상아",
      },
      {
        id: "s1_53",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-08",
        time: "18:30",
        event: "",
        actors: "박민성, 강병훈, 이상아",
      },
      {
        id: "s1_54",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-09",
        time: "15:00",
        event: "",
        actors: "김지철, 안지환, 유낙원",
      },
      {
        id: "s1_55",
        showName: "시데레우스",
        place: "플러스씨어터",
        date: "2026-08-09",
        time: "18:30",
        event: "",
        actors: "김지철, 정휘, 유낙원",
      },
    ],
  },
];

export const myFriends = [
  {
    id: "friend1",
    name: "김뮤덕",
    schedules: [
      {
        id: "f1_1",
        title: "시데레우스 관극",
        date: "2026-06-17",
        time: "20:00",
        genre: "뮤지컬",
        isPending: false,
        actors: "최호승 회차",
        place: "플러스씨어터",
      },
    ],
  },
  {
    id: "friend2",
    name: "이연극",
    schedules: [
      {
        id: "f2_1",
        title: "등등곡 자첫",
        date: "2026-06-24",
        time: "20:00",
        genre: "뮤지컬",
        isPending: false,
        actors: "안지환 회차",
        place: "예스24스테이지 1관",
      },
    ],
  },
  {
    id: "friend3",
    name: "박동연",
    schedules: [
      {
        id: "f3_1",
        title: "오펀스 밤공",
        date: "2026-06-24",
        time: "20:00",
        genre: "연극",
        isPending: false,
        actors: "우현주 회차",
        place: "대학로 아트원씨어터",
      },
    ],
  },
  {
    id: "friend4",
    name: "최스릘",
    schedules: [
      {
        id: "f4_1",
        title: "딜 바이 마우스",
        date: "2026-06-24",
        time: "20:00",
        genre: "연극",
        isPending: false,
        actors: "김재범, 정재환",
        place: "대학로 콘텐츠그라운드",
      },
    ],
  },
  {
    id: "friend5",
    name: "정오페라",
    schedules: [
      {
        id: "f5_1",
        title: "미오 프라텔로",
        date: "2026-06-24",
        time: "20:00",
        genre: "뮤지컬",
        isPending: false,
        actors: "정동화, 안창용, 주민진",
        place: "대학로 링크아트센터",
      },
    ],
  },
];

const hashCode = (str) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = hash * 31 + str.charCodeAt(i);
    hash = hash & hash;
  }
  return Math.abs(hash);
};

export const getPersonColor = (id) => {
  if (id === "me") return { bg: "#475569", color: "#ffffff" };
  if (id === "actor1") return { bg: "#7c5a9e", color: "#ffffff" };
  if (id === "actor2") return { bg: "#5275a1", color: "#ffffff" };
  if (id === "actor3") return { bg: "#a6526d", color: "#ffffff" };
  if (id === "actor4") return { bg: "#4d724d", color: "#ffffff" };

  const hash = hashCode(id);
  const hueShift = (hash * 137) % 360;
  return { bg: `hsl(${hueShift}, 45%, 50%)`, color: "#ffffff" };
};
